### PR TITLE
[12.0][IMP] rma: Add customer as suggested recipient

### PR DESCRIPTION
**Pull request by ernestotejeda**
cc @Tecnativa TT27024

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
What happens if the customer is already a follower? Is it suggested again?

**Comment by ernestotejeda** [comment]
No, in that case the customer is not suggested.

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
FW-port it to v13

**Pull request closed without merging**
