### PR TITLE
[13.0][IMP] rma_sale: Set sale_line_id to refund line.

### PR DESCRIPTION
**Pull request by victoralmau**
Set sale_line_id to refund line.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What is the use case? Putting the first invoice found doesn't feel correct.

**Comment by victoralmau** [comment]
> What is the use case? Putting the first invoice found doesn't feel correct.

The use case would be:
- Sales order is confirmed.
- Products are shipped.
- Invoice is created.
- RMA is created.
- Refund invoice is done from RMA.

IMO this refund should be linked to the initial invoice.

**Comment by pedrobaeza** [comment]
Not really, as it's not a reversed entry. It happens the same if you return a product, and make the refund of such return: no reverse entry is linked. The important thing is that the same sales line is linked in both invoice and refund, which is already happening, isn't it?

**Comment by victoralmau** [comment]
Ok, checking in runboat the field `sale_line_ids` (in the invoice line) is not being defined in the refund created from RMA.

**Comment by pedrobaeza** [comment]
Then that's the thing to fix

**Comment by victoralmau** [comment]
Changes done.

**Comment by pedrobaeza** [comment]
Oh, wait, I'm remembering that this was discarded because if not, the SO is put again as invoiceable. Can you check the history to see if it's true?

**Comment by victoralmau** [comment]
You are absolutely right, I have tested it with this change applied and it is just what happens (the SO is put again as invoiceable).

**Pull request closed without merging**
