### PR TITLE
[ADD][14.0] New module repair_procurement that creates procurements when you confirm a repair order

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've created a new module repair_procurement that creates procurements when you confirm a repair order.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@alan196  I Just wanted to let you know there is a specific repo for repairs: https://github.com/OCA/repair In v14.0 it is ok to use this one but in the migration you can consider to move this module to that repo. Thanks :)

**Comment by pedrobaeza** [comment]
Maybe directly we should create the 14.0 branch in OCA/repair as well.

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza  I thought to make the cut in 15.0 because there are merged modules for repairs in 14.0 in OCA/manufacture, but I am not sure

**Comment by pedrobaeza** [comment]
Well, that modules may be moved on 15.0, but new modules can land already on proper repo.

**Pull request closed without merging**
