### PR TITLE
[IMP] rma: allow to archive operation types

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT30985

please review @pedrobaeza @victoralmau

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And smart-button visualization?

**Comment by chienandalu** [comment]
> And smart-button visualization?

Well, there are not even views or menu available

**Comment by pedrobaeza** [comment]
OK, Travis is failing

**Comment by chienandalu** [comment]
Green now

**Review by victoralmau — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot merge minor

Fw-port it to v13

**Pull request merged**
