### PR TITLE
Update repo readme, update feedback link

### PR DESCRIPTION
**Pull request by osvalr**
It updates repo readme with the last changes

### CODE REVIEW

**Comment by nhomar** [comment]
@osvalr can you dedicate a little bit more to the summary, not only put in separate words what the module name is. please.

**Comment by yaniaular** [comment]
@osvalr The comments of @nhomar are ready?

**Comment by nhomar** [comment]
@osvalr is this PR till valid?

**Comment by osvalr** [comment]
Hi @nhomar @yaniaular no, it's not.

I prefer to wait until all PR be merged to continue doing this

**Comment by nhomar** [comment]
@osvalr please rebase and update.

**Comment by yaniaular** [comment]
@nhomar @pedrobaeza Please review and merge . thanks a lot!

**Comment by yaniaular** [comment]
:+1:

**Comment by gurneyalex** [comment]
@yaniaular @nhomar unless I'm mistaken the descriptions in the readme are read from the **openerp**.py files so these changes will be overwritten when the update script is run on the module. 

@sbidoul do you confirm?

**Comment by sbidoul** [comment]
The `Available addons` and `Unported addons` sections in README.md are generated nightly from the content of `__openerp__.py` yes.

**Comment by moylop260** [comment]
@yaniaular 
From section `[//]: # (addons)` to `[//]: # (end addons)` you shouldn't modify nothing because is auto-generated.

Remove the following diff:
http://screenshots.vauxoo.com/oem/b730e8-1347x791.png

**Comment by yaniaular** [comment]
Thanks @moylop260 @sbidoul @gurneyalex

**Comment by yaniaular** [comment]
@nhomar @pedrobaeza @gurneyalex  Please review and merge .

**Pull request merged**
