### PR TITLE
[15.0][OU-ADD] rma: Add migration script.

### PR DESCRIPTION
**Pull request by victoralmau**
Add migration script.

Please @chienandalu and @pedrobaeza can you review it?

@Tecnativa TT37300

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
You have to delete the translations with the `openupgradelib` function of the changed templates.

**Comment by victoralmau** [comment]
Changes done.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
