### PR TITLE
[IMP] rma: optionally group returns to customer

### PR DESCRIPTION
**Pull request by chienandalu**
By default, returns to customer are grouped by shipping address, warehouse and company.
If you want to avoid this grouping you can:

- Go to *Settings > Inventory*.
- Set *Group RMA returns by customer address and warehouse* checkbox off.

The users will still be able to group those pickings from the wizard.

cc @Tecnativa TT34806

please review @ernestotejeda @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by ernestotejeda — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot migration minor

Please fw-port it to v14

**Comment by chienandalu** [comment]
The bot didn't merge

**Comment by chienandalu** [comment]
Ops. This one is still open. Can you try to merge again?

**Pull request merged**
