### PR TITLE
[14.0][FIX] rma

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by Freni-OSI** [comment]
#304

**Review by chienandalu — APPROVED** [review]
Thanks! :+1: 

ping @victoralmau

**Review by victoralmau — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this needed in v15?

**Comment by chienandalu** [comment]
> Is this needed in v15?

It's solved (with sudo): https://github.com/OCA/rma/blob/15.0/rma/models/rma.py#L825

**Pull request merged**
