### PR TITLE
[13.0][FIX] website_rma: remove default space characters in website form description input

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT27062

### CODE REVIEW

**Comment by ernestotejeda** [comment]
@bodedra @chienandalu @pedrobaeza @joao-p-marques Could you review, please?

**Review by pedrobaeza — APPROVED** [review]

**Review by joao-p-marques — APPROVED** [review]

**Review by bodedra — APPROVED** [review]
Functional reviewed. :+1:

**Pull request merged**
