### PR TITLE
[14.0][MIG] rma_delivery

### PR DESCRIPTION
**Pull request by ghost**
migration to 14.0:
I had some problems with the pre-commit hooks:
I had to comment out prettier otherwise it deletes the content of eg. res_config_settings_views.xml

Bildschirmfoto 2022-12-15 um 15 24 32

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It's not correct to remove the prettier XML. Check that indentations in the XML are correct.

**Comment by ghost** [comment]
Thanks for the hint - there was one file which I didn't touch with intentation problems because of this file all xmls where deleted. Should work now, with the prettier config intact.

**Comment by pedrobaeza** [comment]
You must split the migration commit from the pre-commit changes.

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration rma_delivery

**Review by chienandalu — APPROVED** [review]
Tested :+1: 

Thanks!

**Pull request merged**
