### PR TITLE
[14.0][ADD] rma_employee

### PR DESCRIPTION
**Pull request by FrankC013**
Creation of a new module to add the employee field within the RMA model

### CODE REVIEW

**Comment by FrankC013** [comment]
@eantones Please review!

**Review by eantones — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Which is the goal of using employees instead of users? Isn't this module a bit stripped without no extra features except the field?

**Comment by FrankC013** [comment]
The objective of this module is to allow the user to assign an RMA to an employee. It's a purely informational field. It's created in a separate module to avoid the installation of HR when someone installs the RMA.

**Comment by pedrobaeza** [comment]
But I insist: why not assigning a user instead?

**Pull request closed without merging**
