### PR TITLE
[17.0][MIG] rma_lot: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 162145
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/rma/issues/376

Depends on:

- [stock_picking_return_lot] https://github.com/OCA/stock-logistics-workflow/pull/1745

### CODE REVIEW

**Comment by rousseldenis** [comment]
@peluko00 Thanks for this.

FYI, you can embed depending PR's following: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

This allows to:

- Run tests
- Run runboat and allows functional review

**Comment by rousseldenis** [comment]
To improve review process, don't hesitate to add link to depending PR in this description

**Comment by peluko00** [comment]
> @peluko00 Thanks for this.
> 
> FYI, you can embed depending PR's following: https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29
> 
> This allows to:
> 
> * Run tests
> * Run runboat and allows functional review

Of course, i'll do it!

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Comment by peluko00** [comment]
It's ready to be merge @rousseldenis?

**Review by BernatObrador — APPROVED** [review]
LGMT, tested in runboat and code review

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
