### PR TITLE
70 add prepare methods

### PR DESCRIPTION
**Pull request by bguillot**
Hello, 

This PR adds prepare methods in the wizard claim_make_picking.

It creates also a procurement (needed for reordering or manufacturing the sended product).

### CODE REVIEW

**Comment by bguillot** [comment]
After some fixes, Travis failed only because of other modules.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by bguillot** [comment]
Can someone merge this PR please ?

Thanks in advance !

**Comment by pedrobaeza** [comment]
Done

**Comment by bguillot** [comment]
Thank you !

**Pull request merged**
