### PR TITLE
[13.0][MIG] website_rma: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
cc @Tecnativa TT27062

### CODE REVIEW

**Review by joao-p-marques — COMMENTED** [review]
Code and functional review :+1: LGTM

Please check Travis

**Comment by ernestotejeda** [comment]
Travis is green. 
ping @joao-p-marques , @chienandalu

**Review by joao-p-marques — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
