### PR TITLE
[IMP] add hook to override field and picking type

### PR DESCRIPTION
**Pull request by bguillot**
Hi

This PR adds a hook method to be able to override the written field in the wizard that creates a picking from the claim.
The PR that used this hook will come next (in the module crm_rma_stock_location)

Thanks for your reviews

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
Ok for me, travis is red to due pep 8 issue that was already there so not blocking for that PR

**Comment by pedrobaeza** [comment]
For fixing Travis you just need to change the use of 2 evals. Please do it and we leave a green one.

**Comment by rousseldenis** [comment]
@bguillot

**Comment by rousseldenis** [comment]
@bguillot Could you rebase?

**Pull request closed without merging**
