### PR TITLE
[14.0] [MIG] rma_sale module

### PR DESCRIPTION
**Pull request by chafique-delli**

### CODE REVIEW

**Comment by chafique-delli** [comment]
@pedrobaeza , ping

**Comment by vinwang1114** [comment]
May I know when the RMA module would be available for Odoo 14?

**Comment by pedrobaeza** [comment]
@vinwang1114 https://odoo-community.org/page/review

**Comment by chienandalu** [comment]
Can you include 7c9b6bc3a8da71ee7d372f160d96625f66d60dc0 and 04f7f0638faaa8e4aaa4a9dd3be6a5e60788f848?

**Comment by florian-dacosta** [comment]
@chienandalu PR has been updated with last changes on v13
I guess it is ready to review
@ernestotejeda

**Review by ernestotejeda — APPROVED** [review]
Code and functional review: OK

**Review by florian-dacosta — APPROVED** [review]
Code review

**Pull request merged**
