### PR TITLE
[ADD] New crm_claim_rma_config module to configurate data for the RMA…

### PR DESCRIPTION
**Pull request by yaniaular**
… operations.

### CODE REVIEW

**Comment by yaniaular** [comment]
We are working on this PR to make it perfect to merge with OCA/rma. 
The modules presented here are part of a collection of modules for the operations of <a href="https://github.com/vauxoo/rma">RMA improved by Vauxoo</a>. Each module will be presented in separate PRs because the PR #26  was too heavy for review.. Some dependencies needed.

**Comment by pedrobaeza** [comment]
Why don't integrate this on the main crm_claim_rma module?

**Comment by yaniaular** [comment]
@pedrobaeza The <a href="https://github.com/Vauxoo/rma/blob/8.0/crm_claim_rma/__openerp__.py#L32">crm_claim_rma</a> module in Vauxoo/rma depends of  crm_claim_rma_config, product_warranty, crm_rma_location_rma. I would do a separate pull request because the crm_claim_rma module is very heavy. Further, crm_claim_rma has the PR #32 pending with @aristobulo-eezee. Which, we'll make appropriate comments to add improvements made in crm_claim_rma of Vauxoo with that.

**Comment by pedrobaeza** [comment]
Yeah, but on contrary, I see this module very weak as "config" and it mixes some concepts:
- It adds a claim type model. This can be done in a module called _crm_claim_type_ and put it on OCA/crm, so other modules can benefit from this. Put it then as dependency for crm_claim_rma.
- It adds a sequence type, that it's not used by the module itself. The sequence should be on crm_claim_rma.
- It adds three types of claims, that aren't used also here. This light file can be also hosted in crm_claim_rma.

**Comment by nhomar** [comment]
@yaniaular I am agreed with @pedrobaeza can you proceed on that way please?

Regards.

**Comment by osvalr** [comment]
@nhomar I am now working on suggestions made by @pedrobaeza

**Comment by yaniaular** [comment]
@pedrobaeza @nhomar @osvalr 

<pre>- It adds a claim type model. This can be done in a module called crm_claim_type and put it on OCA/crm, so other modules can benefit from this. Put it then as dependency for crm_claim_rma.</pre>

Made in https://github.com/OCA/crm/pull/39

<pre>- It adds a sequence type, that it's not used by the module itself. The sequence should be on crm_claim_rma.
- It adds three types of claims, that aren't used also here. This light file can be also hosted in crm_claim_rma.</pre>

Made in https://github.com/vauxoo-dev/rma/tree/8.0-squash_crm_claim_rma also will be proprosed to the OCA/rma.

<b>This PR can be closed, the crm_claim_rma_config is deprecated.</b>

**Pull request closed without merging**
