### PR TITLE
[8.0][FIX] .travis: Update to latest template

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
#124 errors

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking this:

/ocabot merge

**Comment by pedrobaeza** [comment]
Can you please fix these po errors?
```
./crm_rma_claim_make_claim/i18n/es.po:23: end-of-line within string
./crm_rma_claim_make_claim/i18n/es.po:23:3: syntax error
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "Para" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "un" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "reclamo" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "a" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "cliente" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "corresponde" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "a" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "los" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "reclamos" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "a" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "proveedor" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "que" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "fueron" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "generados" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "a" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "partir" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "de" unknown
./crm_rma_claim_make_claim/i18n/es.po:23: keyword "l" unknown
./crm_rma_claim_make_claim/i18n/es.po:24: end-of-line within string
```

**Comment by rousseldenis** [comment]
Mmmh, maybe wrong base branch. Will check

**Comment by pedrobaeza** [comment]
Well, it's mostly that previously PO integrity was not checked (neither in this PR, as MAKEPOT only acts on main branches).

**Comment by rousseldenis** [comment]
So, as every new PR on 8.0 will fail, I will try to have time to do it

**Pull request merged**
