### PR TITLE
[IMP] rma: tags

### PR DESCRIPTION
**Pull request by chienandalu**
Now with tags :slightly_smiling_face: 
image

TT29594

ping @pedrobaeza @victoralmau

### CODE REVIEW

**Review by victoralmau — CHANGES_REQUESTED** [review]
Good job.
Please, add color field in tags view.
Add some tests about it (or add some tags and use it in actual tests).

**Comment by chienandalu** [comment]
> Please, add color field in tags view.

Normally this is done via the many2many_tags widget. Having it on the form I think is a bit misleading as the user doesn't know which index corresponds to what color

**Comment by chienandalu** [comment]
> Add some tests about it (or add some tags and use it in actual tests).

As for this, there's no logic added, so the test would be kinda dummy, don't you think?

**Review by victoralmau — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please translate it when merged and fw-port it to v13:

/ocabot merge minor

**Pull request merged**
