### PR TITLE
[8.0 FIX] Fixes returned quantity

### PR DESCRIPTION
**Pull request by levkar**
Adding this field makes quantity work as it is expected

### CODE REVIEW

**Comment by rubencabrera** [comment]
Edited my comment. Yes, this works fine!
The quantity is correctly added to the claim line (but there's still something wrong with the new returns created from the claim).

**Comment by levkar** [comment]
If you can explain your findings (if you think it is related) we can take a look.

**Comment by rubencabrera** [comment]
Please excuse my stupidity, it gets worse on Mondays. It works like a charm!

**Comment by pedrobaeza** [comment]
Can you check Travis?

**Comment by levkar** [comment]
I am having hard time resolving checks. I thought it is because of compute but I was wrong. Is it this line?

self.assertEquals(eval(res['context'])['type'], 'out_refund')

If it is, then I'm not sure how to fix it. This is not related to my commit anyway.

I get discouraged when i fix something and get stuck for other reasons when i try to contribute back. Maybe we should practice full-oca-compliant CI cycle in our company to improve our contributions.

Don't get me wrong, this is not a complaint, just how I feel and think.

**Comment by gurneyalex** [comment]
superseesed by #121

**Pull request closed without merging**
