### PR TITLE
[IMP][FIX] Forward ports from v12.0

### PR DESCRIPTION
**Pull request by chienandalu**
Converge with v12 state of the art

cc @Tecnativa @ernestotejeda @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Check pre-commit

**Comment by pedrobaeza** [comment]
(wrong button, sorry)

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by ernestotejeda — APPROVED** [review]

**Pull request merged**
