### PR TITLE
[16.0][MIG] rma_sale_mrp: Migration to version 16.0

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Standard procedure.
- Rename changed fields.

@Tecnativa TT44949

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@chienandalu please review if any change for the portal or report thing associated to BS5 is needed.

**Review by chienandalu — APPROVED** [review]
Tested and added bs4 -> bs5 adaptations

**Review by victoralmau — APPROVED** [review]
Functional review OK

**Pull request merged**
