### PR TITLE
[FIX] rma: internal users portal

### PR DESCRIPTION
**Pull request by chienandalu**
Internal users with no RMA permissions got an access error when entering
the portal

cc @Tecnativa TT26338

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't rma_count be 0 in that case?

**Comment by chienandalu** [comment]
Sure, that could be better. I was also thinking in another aproach with a try/expect so we don't depend on specific groups, what do you think?

**Comment by pedrobaeza** [comment]
How is this handled in core?

**Review by victoralmau — COMMENTED** [review]
IMO if is possible to add this groups in template https://github.com/OCA/rma/blob/12.0/rma/views/rma_portal_templates.xml#L17 is a better solution. What do you think about it?

And maybe too, can be interesting add some redirections in https://github.com/OCA/rma/blob/12.0/rma/controllers/main.py#L34 if user haven't some groups.

**Comment by chienandalu** [comment]
> How is this handled in core?

They don't handle it at all, wich provokes access errors if the internal user doesn't have the proper permissions.

**Comment by pedrobaeza** [comment]
@chienandalu I don't think that happen: if a user don't have sales permissions for example, is there an error on /my?

**Comment by chienandalu** [comment]
An example with purchases:
```
odoo.exceptions.AccessError: ('Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Inventory/User\n\t- Accounting & Finance/Billing\n\t- Purchases/User\n\t- Purchases/Manager\n\t- User types/Portal\n\n(Document model: purchase.order) - (Operation: read, User: 6)', None)
```
image

**Comment by pedrobaeza** [comment]
Ouch, that hurts... I think we can report it to Odoo. Anyway, for this, take the approach you consider more suitable.

**Comment by chienandalu** [comment]
Changes done

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Oh, another doubt: what happen if you go with one of these users to /my/rma or click the link of 0 RMAs?

**Comment by chienandalu** [comment]
Sure. They'll get a forbidden. The solution here should be to not show it if there aren't RMAs

**Comment by pedrobaeza** [comment]
Yes, that's why I talked about putting a group in the template. I'm pretty sure that's possible even in QWeb templates.

**Comment by chienandalu** [comment]
There goes the fix

**Comment by pedrobaeza** [comment]
Any way, let's go with this fair solution:

/ocabot merge minor

**Comment by chienandalu** [comment]
In this case, is the way Odoo does it in core

**Pull request merged**
