### PR TITLE
[15.0][MIG] rma: Migration to 15.0

### PR DESCRIPTION
**Pull request by ghost**
migration + tests

### CODE REVIEW

**Comment by ghost** [comment]
Just to make sure. It's absolutely necessary to get to 98,48 % test coverage? Because it seams a big step from the 70 % in v14 to almost 100 %.

**Comment by pedrobaeza** [comment]
No, you don't have to worry in migrations about coverage.

**Comment by ghost** [comment]
Is there anything I can do to speed up the migration to 15.0? How long will the review process take approximately?

**Comment by chienandalu** [comment]
Sorry, I was waiting to forward port some stuff up to 14.0. Can you included the following?:

- e4e81d501e6712ac56377498ba17d127fa5dcd80
- eadf34e6f758ba1555e974dc6f21d2d94f5ff782
- a51efbd6b4cc6fc0efa6b0c9ba554e0345d9f803

**Comment by jacekmichalski** [comment]
Hi, I'm also interested in this migration. @nikolausweingartmair are you still working on this?

**Comment by ghost** [comment]
@jacekmichalski: Yes, had some problems with the commit history. I created a new pull request: [https://github.com/OCA/rma/pull/285](https://github.com/OCA/rma/pull/285)

**Pull request closed without merging**
