### PR TITLE
[FIX] File naming of view files

### PR DESCRIPTION
**Pull request by yaniaular**
File naming of view files according to https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#file-naming

### CODE REVIEW

**Comment by moylop260** [comment]
👍

**Comment by pedrobaeza** [comment]
The same reasoning as in https://github.com/OCA/maintainer-tools/pull/191#issuecomment-219632602, so :-1: for me

**Comment by elicoidal** [comment]
:+1:

**Comment by osvalr** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
