### PR TITLE
[IMP] rma: automatic notification subtypes

### PR DESCRIPTION
**Pull request by chienandalu**
Allow users to unsubscribe from automatic notifications

cc @Tecnativa TT28344

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What about migration scripts? With this, messages will be internal, which doesn't seem correct for customer messages.

**Comment by chienandalu** [comment]
> What about migration scripts? 

Should we subscribe users by default or maybe take the default from the other notification type?

> With this, messages will be internal, which doesn't seem correct for customer messages.

Well, is not really internal but, in Odoo's terms, "not discussion". It's a pity that it's so hard linked to a specific subtype: https://github.com/odoo/odoo/blob/12.0/addons/mail/static/src/xml/thread.xml#L279
https://github.com/odoo/odoo/blob/12.0/addons/mail/models/mail_message.py#L525

**Comment by pedrobaeza** [comment]
But the customer receives the message as "Internal message: replies will only be seen by employees..."?

**Comment by chienandalu** [comment]
No:

image

**Comment by pedrobaeza** [comment]
Are migration scripts needed?

**Comment by chienandalu** [comment]
I don't think so

**Review by pedrobaeza — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
