### PR TITLE
[FIX] Do not put lines that have products of type 'service' in the st…

### PR DESCRIPTION
**Pull request by daramousk**
…ock_moves

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why a claim should contain services products?

Please change module version numbers

**Comment by daramousk** [comment]
Well, can't a user make a claim on a service provided by my company?

**Comment by pedrobaeza** [comment]
This is not claim management, but RMA, where returned stock is involved. Any way, I let others to decide.

**Comment by daramousk** [comment]
@pedrobaeza I understand, will close this since it is not appropriate in rma.

Thanks for your time!

**Pull request closed without merging**
