### PR TITLE
[18.0][MIG] product_warranty: Migration to 18.0 

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 18.0

cc https://github.com/APSL 163293
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/rma/issues/425

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]

**Comment by peluko00** [comment]
Seems it's ready to merge @rousseldenis

**Pull request merged**
