### PR TITLE
[14.0][FIX] rma*, fix action permission issues.

### PR DESCRIPTION
**Pull request by GSLabIt**

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Comment by chienandalu** [comment]
Thanks! It'd be nice to have a commit per module though

**Comment by GSLabIt** [comment]
> Thanks! It'd be nice to have a commit per module though

done

**Comment by chienandalu** [comment]
Great :)

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
