### PR TITLE
[14.0][FIX] rma + rma_sale: Allow to create an RMA to a user  with access_token to sale order (no user created).

### PR DESCRIPTION
**Pull request by victoralmau**
Changes:
- Allow to create an RMA to a user  with `access_token` to sale order (no user created).
- Show RMA's list (with share url) to a user with access_token to sale order (no user created).

Please @chienandalu and @ernestotejeda can you review it?

@Tecnativa

### CODE REVIEW

**Comment by victoralmau** [comment]
Already merged at https://github.com/OCA/rma/pull/284

**Comment by pedrobaeza** [comment]
Where it has been merged?

**Comment by victoralmau** [comment]
Sorry, it was merged at https://github.com/OCA/rma/pull/284

**Comment by pedrobaeza** [comment]
OK, then sorry, as I didn't see yours.

**Pull request closed without merging**
