### PR TITLE
[rma] adding po file spanish translation draft

### PR DESCRIPTION
**Pull request by Galoperd**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use Weblate instead: https://odoo-community.org/blog/the-oca-blog-1/post/translations-platform-81

**Comment by Galoperd** [comment]
Hi, cannot use Weblate because the po files are not there for v.12.

**Comment by rousseldenis** [comment]
Hi @pedrobaeza, it seems, even if some modules are merged in v12, that weblate entry is missing :

image

**Comment by pedrobaeza** [comment]
That's because some PO files are not correct. Travis is red due to this:

https://travis-ci.org/OCA/rma/builds/564794290

Specifically, the errors is in https://travis-ci.org/OCA/rma/jobs/564794292#L1159

Someone must fix it for being in Weblate.

**Comment by Galoperd** [comment]
I would be glad to do this but I do not have edit access rights to the OCA\rma repository.

**Comment by pedrobaeza** [comment]
To solve it you have to do the same as here: create a pull request with the .po fixed

**Pull request closed without merging**
