### PR TITLE
[16.0] [MIG] rma

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Murtaza-OSI Thanks for this. Could you follow migration guide (especially full process) ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

Your commit message for pre-commit fixes should be renamed

**Comment by pablontura** [comment]
Functional review. If I try to replace a product or access the RMA smartbutton in the original shipment, I get these errors:

reemplazo
Smartbutton

**Comment by rousseldenis** [comment]
@Murtaza-OSI Could you fix tests ?

**Comment by agyamuta** [comment]
> @Murtaza-OSI Could you fix tests ?

@Murtaza-OSI can you please check on this and fix? Thank you.

**Comment by Murtaza-OSI** [comment]
> Functional review. If I try to replace a product or access the RMA smartbutton in the original shipment, I get these errors:
> 
> reemplazo Smartbutton

Issue fix pls check

**Comment by QubiQBcn** [comment]
> > Functional review. If I try to replace a product or access the RMA smartbutton in the original shipment, I get these errors:
> > reemplazo Smartbutton
> 
> Issue fix pls check

The smartbutton is now working, but I keep getting the same error when doing a replace...

ErrorRMA

**Comment by agyamuta** [comment]
@Murtaza-OSI can you please work on this again? Thanks.

**Comment by pedrobaeza** [comment]
Superseded by the CI-green PR and with heavy refactoring #361. Please review it.

**Pull request closed without merging**
